spring:
    datasource:
        url: jdbc:mysql://localhost:3306/Grupo-20-BDD-OO2-2021?serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
    jpa:  
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate:
                format_sql: true              
    mvc:
      contentnegotiation:
        favor-parameter: true
        media-types.pdf: application/pdf
        
      
                